services:
  app:
    container_name: task-manager-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # Load environment variables from .env file
    env_file:
      - .env
    environment:
      # Pass the port env var to the container so Next.js uses it
      - APP_PORT=${APP_PORT}
    ports:
      # Map Host Port : Container Port
      - '${APP_PORT}:${APP_PORT}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
